<?php

namespace App;

class Constants
{
    const CATEGORIA = [
        1 =>    'ENTRADA',
        2 =>    'HATCH PEQUENO',
        3 =>    'HATCH MÉDIO',
        4 =>    'SEDANS PEQUENO',
        5 =>    'SEDANS COMPACTOS',
        6 =>    'SEDANS MÉDIO',
        7 =>    'SEDANS GRANDES',
        8 =>    'SUV',
        9 =>    'SW MÉDIO',
        10 =>    'SW GRANDE',
        11 =>    'MONOCAB',
        12 =>    'GRANCAB',
        13 =>    'SPORTS',
        14 =>    'PICK-UPS PEQUENOS',
        15 =>    'PICK-UPS GRANDES',
        16 =>    'FURGÕES',
        17 =>    'FURGÕES PEQUENOS',
    ];

    const MARCA = [
         1 => 'ABARTH',
         2 => 'ALFA ROMEO',
         3 => 'ASTON MARTIN',
         4 => 'AUDI',
         5 => 'BENTLEY',
         6 => 'BMW',
         7 => 'CATERHAM',
         8 => 'CHEVROLET',
         9 => 'CHRYSLER',
         10 => 'CITROEN',
         11 => 'CORVETTE',
         12 => 'DACIA',
         13 => 'DAEWOO',
         14 => 'DAIHATSU',
         15 => 'DODGE',
         16 => 'DS',
         17 => 'FERRARI',
         18 => 'FIAT',
         19 => 'FORD',
         20 => 'GALLOPER',
         21 => 'HONDA',
         22 => 'HUMMER',
         23 => 'HYUNDAI',
         24 => 'JAGUAR',
         25 => 'JEEP',
         26 => 'KIA',
         27 => 'LADA',
         28 => 'LAMBORGHINI',
         29 => 'LANCIA',
         30 => 'LAND ROVER',
         31 => 'LEXUS',
         32 => 'LOTUS',
         33 => 'MASERATI',
         34 => 'MAYBACH',
         35 => 'MAZDA',
         36 => 'MERCENDES-BENZ',
         37 => 'MG',
         38 => 'MINI',
         39 => 'MITSUBISHI',
         40 => 'MORGAN',
         41 => 'NISSAN',
         42 => 'OPEL',
         43 => 'PEUGEOT',
         44 => 'PORSCHE',
         45 => 'RENAULT',
         46 => 'ROLLS-ROYCE',
         47 => 'ROVER',
         48 => 'SAAB',
         49 => 'SEAT',
         50 => 'SKODA',
         51 => 'SMART',
         52 => 'SSANG YONG',
         53 => 'SUBARU',
         54 => 'SUZUKI',
         55 => 'TATA',
         56 => 'TESLA',
         57 => 'TOYOTA',
         58 => 'VOLKSWAGEM',
         59 => 'VOLVO'
    ];

    const TIPO_VEICULO = [
         1 => 'bicicleta'  ,
         2 => 'ciclomotor' ,
         3 => 'motoneta'   ,
         4 => 'motocicleta',
         5 => 'triciclo'   ,
         6 => 'quadriciclo',
         7 => 'automóvel'  ,
         8 => 'microônibus',
         9 => 'ônibus'     ,
         10 => 'bonde',
         11 => 'reboque ou semi-reboque',
         12 => 'charrete'
    ];
}